baseURL = "https://www.qword.space/"
languageCode = "en-us"
title = "qword's blog"
theme="archie"
copyright = "© David John"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	mode="auto"
	useCDN=false
	subtitle = "Things about C, C++, Rust, Assembly, Operating Systems and Philosophy"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/qw0rd"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://github.com/athulcajay/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
